image: node:14-buster

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

unit-test-job:
  stage: test
  script:
    - echo "Installing dependencies"  
    - npm install  
    - echo "Running unit tests"
    - npm test

build-job:
  stage: build
  only:
    - main
    - tags
  script:
    - echo "Compiling the code..."
    - npm run build
    - echo "Compile complete."
  artifacts:
    paths:
      - dist
      - package.json
      - readme.md
    expire_in: 1 week

deploy-job:
  stage: deploy
  only:
    - tags
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm config set @izzius94:registry https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/
    - npm config set -- '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${NPM_TOKEN}"
    - npm config set -- '//gitlab.com/api/v4/packages/npm/:_authToken' "${NPM_TOKEN}"
    - echo $NPM_TOKEN
    - cat .npmrc
    - npm publish
    
deploy-npm-job:
  stage: deploy
  only:
    - main
    - tags

  script:
    - echo "$NPM_SCOPE:registry=https://registry.npmjs.org" > .npmrc
    - echo "//https://registry.npmjs.org:_authToken=$NPM_TOKEN" >> .npmrc
    - cat .npmrc
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm set registry https://registry.npmjs.org
    - npm publish --registry https://registry.npmjs.org
