image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

unit-test-job:
  stage: test
  script:
    - echo "Installing dependencies"  
    - npm install  
    - echo "Running unit tests"
    - npm test

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - npm run build
    - echo "Compile complete."
  artifacts:
    paths:
      - dist
      - package.json
      - readme.md
    expire_in: 1 week

deploy-job:
  stage: deploy
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm config set -- '//gitlab.com/api/v4/projects/express-request-validator/packages/npm/:_authToken' "${NPM_TOKEN}"
    - npm config set -- '//gitlab.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm publish
