image: node:14-buster

cache:
  paths:
    - node_modules/

stages:
  - dependencies
  - test
  - build
  - deploy

include:
  - template: Dependency-Scanning.gitlab-ci.yml

install:
  stage: dependencies
  script:
    - echo "Installing dependencies"
    - npm install

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests"
    - npm test

standard-test-job:
  stage: test
  script:
    - echo "Checking standard"
    - npm run check-standard

test-coverage:
  stage: test
  script:
    - npm run coverage
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

gemnasium-dependency_scanning:
  variables:
    DS_REMEDIATE: "false"

build-job:
  stage: build
  only:
    - main
    - tags
  script:
    - echo "Compiling the code..."
    - npm run build
    - echo "Compile complete."
  artifacts:
    paths:
      - coverage
      - dist
      - package.json
      - readme.md
    expire_in: 1 week

deploy-job:
  stage: deploy
  only:
    - tags
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm config set @izzius94:registry https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/
    - npm config set -- '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${NPM_TOKEN}"
    - npm config set -- '//gitlab.com/api/v4/packages/npm/:_authToken' "${NPM_TOKEN}"
    - echo $NPM_TOKEN
    - cat .npmrc
    - npm publish
    
deploy-npm-job:
  stage: deploy
  when: manual
  only:
    - tags
  script:
    - echo "$NPM_SCOPE:registry=https://registry.npmjs.org" > .npmrc
    - echo "//https://registry.npmjs.org:_authToken=$NPM_TOKEN" >> .npmrc
    - cat .npmrc
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm set registry https://registry.npmjs.org
    - npm publish --registry https://registry.npmjs.org

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build-job
      artifacts: true
  script:
    - echo 'release job'
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: './RELEASE.md'
